### ISSUE TITLE
PyPi package should not include pyc files

### ISSUE THREAD

**Issue by DavidLP** [thclark/rstcloth#20]
Otherwise installation [fails](https://stackoverflow.com/questions/30861493/how-to-fix-python-valueerrorbad-marshal-data) on incompatible python versions with something like:
```
ValueError: bad marshal data (unknown type code)
```

**Comment by thclark** [comment]
Thanks @DavidLP - I'm just moving the project to poetry so this should be fixed on next release >0.3.1
