### ISSUE TITLE
Support older version of pyyaml

### ISSUE THREAD

**Issue by elupus** [thclark/rstcloth#38]
Currently library requires PyYaml version 6. Which causes conflicts with other tools like CodeChecker. It would be good if this requirement could be loosened to allow version 5. I can't see any specific reason for it to require version 6.

**Comment by elupus** [comment]
Related issue: https://github.com/Ericsson/codechecker/issues/3924

**Comment by thclark** [comment]
Argh, had a nightmare with a bunch of outdated CD but sorted and released now. You should be good to go in a few minutes @elupus
