### ISSUE TITLE
Spack packaging

### ISSUE THREAD

**Issue by roottreej** [thclark/rstcloth#43]
Hello,
Just a quick question : will you packaging "rstcloth" onto spack (https://spack.readthedocs.io/en/latest/package_list.html) ? 
Something like "py-rstcloth".  
Because if you do it, you probably will have more users, like me.

Thank you for your response.

**Comment by thclark** [comment]
I think it's unlikely; having never heard of spack, a quick google shows it to be most suited for compiled packages (or python modules in which installation involves a compilation stage), with a view to controlling the combination of various dynamically-linked libraries and their architecture-specific compilation options for supercomputing purposes.

There's no built code in rstcloth so I see no benefit at all to creating a python plugin, over the far more straightforward installation from pypi into your spack env.

If there are other users who see the benefit, please do weigh in here and if there's demand for it and a clear use case, I'll re-open :)
