### ISSUE TITLE
Add simple_table feature for direct rst table generation

### ISSUE THREAD

**Issue by joej164** [thclark/rstcloth#44]
Hello,
So I'm looking to automate the Restructured Text generation for a project I have.

We use the simple restructured text tables as opposed to the grid tables.  I had to subclass your library and overwrite your table method with our own in order to use it.

I thought I'd pass on how we're using the table method in case you might want to expose the format and maxcolwidths parameters in your library.

Or I could understand why you wouldn't want to open up everybody to whatever the tabular library supports, but then in that case a "simple_table" method would be nice for outputting simple restructured text tables instead of the grid ones currently.

The ability to set the max width on columns would be helpful as to help with the formatting as the table width doesn't honor the `line_width` parameter when creating the object.

Thanks for your library, hope the feedback helps.

```
from rstcloth import RstCloth
from rstcloth.rstcloth import _indent
from tabulate import tabulate

class MyCloth(RstCloth):
    def table(self, header, data, indent=0, fmt="rst", max_col_widths=None):
        t = tabulate(
            tabular_data=data, headers=header, tablefmt=fmt, disable_numparse=True, maxcolwidths=max_col_widths
        )
        self._add("\n" + _indent(t, indent) + "\n")

out = io.StringIO("")

# Generate the Restructured Text Doc String
docstring = MyCloth(line_width=100, stream=out)
table_data = [
    ["thing1", "thing2", "thing3"],
    ["thing4", "thing5", "thing6           this is a really long piece of data that i want lots of length so I can show off the useful wordwrap that occurs on very long strings"]
]
docstring.table(["Parameter", "Type", "Description"], table_data, indent=4, max_col_widths=[None, None, 100])
print(docstring.data)

```

```
    ===========  ======  =================================================================================================
    Parameter    Type    Description
    ===========  ======  =================================================================================================
    thing1       thing2  thing3
    thing4       thing5  thing6           this is a really long piece of data that i want lots of length so I can show off
                         the useful wordwrap that occurs on very long strings
    ===========  ======  =================================================================================================

```

NOTE: Edited a couple of times to add a full working example.  The above should be working code, but gives you a better idea of how we're using it.

**Comment by thclark** [comment]
Thanks, it's really helpful to have great feedback like that!

Next time I'm doing a chunk of work, I'll look at turning this into a `simple_table` method and adding that to the docs - I would accept a PR for it if you're impatient!

**Comment by thclark** [comment]
Job done - thanks @joej164. If you feel like becoming a regular contributor I'll happily add you to the maintainers list :)

**Comment by joej164** [comment]
Hello,

Sorry for the delay, I saw this when I was away from my computer, then kept
forgetting to get back to it.

Thanks for the offer.  I found your library because I was trying to
templatize some code for a work project.  I don't do that much with
restructured text tables outside of that project, otherwise I'd take you up
on the offer.

Joe
